# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

sudo: true

language: c

env:
   global:
     - CRAN: http://cran.rstudio.com
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - _R_CHECK_FORCE_SUGGESTS_=FALSE
     - BOOTSTRAP_LATEX=""
     - NOT_CRAN="true"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install netcdf-bin libproj-dev libgdal1-dev
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_r devtools
  - ./travis-tool.sh install_r testthat
  - ./travis-tool.sh install_r sp
  - ./travis-tool.sh install_r rgdal
  - ./travis-tool.sh install_r raster
  - ./travis-tool.sh install_r chron
  - ./travis-tool.sh install_r zoo
  - ./travis-tool.sh install_r PCICt
  - ./travis-tool.sh install_r SDMTools
  - ./travis-tool.sh install_r climdex.pcic
  - ./travis-tool.sh install_r ncdf
  - ./travis-tool.sh install_r ncdf4
  # - ./travis-tool.sh install_r clim.pact
  
r_github_packages:
 - jimhester/covr
script: ./travis-tool.sh run_tests

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
